### ISSUE TITLE
On opening invite packet in method it shows it as invite. but in Line it shows it as 200 OK.

### ISSUE THREAD

**Issue by naqashsaeed** [metrico/grafana-flow#67]
Hi, I have tested new version of grafana-flow. I notice one thing that when we open an invite packet, in method it shows it as invite. but in Line, it shows it as 200 OK.
![image](https://github.com/metrico/grafana-flow/assets/110665986/b80811a7-856e-433c-8260-767045176ced)

**Comment by lmangani** [comment]
@AlexeyOplachko please reproduce and fix

**Comment by AlexeyOplachko** [comment]
This looks to be a confusion due to label naming `method` label refers to method in CSeq, while `response` label is method is stated in Request-Line
Evident from following excerpts from code in helpify-server

[Source](https://github.com/sipcapture/heplify-server/blob/fc183320ed1319736d3a13a8b1c8e7a36fc0a9c6/metric/prometheus.go#L75)
```go
methodResponses.WithLabelValues(srcTarget, "src", pkt.NodeName, pkt.SIP.FirstMethod, pkt.SIP.CseqMethod).Inc()
```
Note that FirstMethod (method in Request-Line [set here](https://github.com/sipcapture/heplify-server/blob/master/sipparser/parser.go#L552)) is set in 4th argument and Cseq method is set in 5th argument

[Source
](https://github.com/sipcapture/heplify-server/blob/master/metric/definition.go#L18)
```go
methodResponses = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "heplify_method_response",
		Help: "SIP method and response counter"},
		[]string{"target_name", "direction", "node_id", "response", "method"})
```

And here you can see that `response` label is 4th in a struct and `method` is 5th
